GET http://localhost:8080/users

###
POST http://localhost:8080/insert 
content-type: application/json

{
    "name": "rohn"
}

###
POST http://localhost:8080/users/login 
content-type: application/json

{
    "name": "john",
    "password": "mypas"
}